# Generated by Django 5.0.7 on 2024-08-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_option1_alter_question_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('choice', 'Multiple Choice'), ('text', 'Text Input')], default='choice', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
